export default

  [
    {
      "id": 1,
      "project_idfk": 111222,
      "survey_manager": "Rob Cross",
      "spread_num": 1,
      "spread_city": "Houston",
      "spread_state": "TX",
      "supervisor_name": "Luther Bodey",
      "supervisor_id": 82350,
      "per_diem": 115,
      "mileage": 0.54,
      "vehicle": false,
      "computer": false,
      "phone": false,
      "utv": false,
    },
    {
      "id": 2,
      "project_idfk": 111333,
      "survey_manager": "James Weston",
      "spread_num": 1,
      "spread_city": "San Antonio",
      "spread_state": "TX",
      "supervisor_name": "Gaston Doyle",
      "supervisor_id": 47993,
      "per_diem": 130,
      "mileage": 0.54,
      "vehicle": false,
      "computer": false,
      "phone": false,
      "utv": false,
    },
    {
      "id": 3,
      "project_idfk": 111333,
      "survey_manager": "James Weston",
      "spread_num": 2,
      "spread_city": "San Marcos",
      "spread_state": "TX",
      "supervisor_name": "Keith Schiller",
      "supervisor_id": 70538,
      "per_diem": 115,
      "mileage": 0.54,
      "vehicle": false,
      "computer": false,
      "phone": false,
      "utv": true,
    },
    {
      "id": 4,
      "project_idfk": 111333,
      "survey_manager": "James Weston",
      "spread_num": 3,
      "spread_city": "Austin",
      "spread_state": "TX",
      "supervisor_name": "Robert Poe",
      "supervisor_id": 64801,
      "per_diem": 180,
      "mileage": 0.54,
      "vehicle": false,
      "computer": false,
      "phone": false,
      "utv": false,
    },
    {
      "id": 5,
      "project_idfk": 111444,
      "survey_manager": "John Boland",
      "spread_num": 1,
      "spread_city": "Oklahoma City",
      "spread_state": "Oklahoma",
      "supervisor_name": "Robert Martin",
      "supervisor_id": 64801,
      "per_diem": 120,
      "mileage": 0.54,
      "vehicle": false,
      "computer": true,
      "phone": true,
      "utv": false,
    },
    {
      "id": 6,
      "project_idfk": 111444,
      "survey_manager": "John Boland",
      "spread_num": 2,
      "spread_city": "Stillwater",
      "spread_state": "Oklahoma",
      "supervisor_name": "Joshua Phillips",
      "supervisor_id": 80151,
      "per_diem": 110,
      "mileage": 0.54,
      "vehicle": false,
      "computer": true,
      "phone": true,
      "utv": false,
    },
    {
      "id": 7,
      "project_idfk": 111444,
      "survey_manager": "John Boland",
      "spread_num": 3,
      "spread_city": "Tulsa",
      "spread_state": "Oklahoma",
      "supervisor_name": "Jarrett Forman",
      "supervisor_id": 65124,
      "per_diem": 115,
      "mileage": 0.54,
      "vehicle": false,
      "computer": true,
      "phone": true,
      "utv": false,
    },
    {
      "id": 8,
      "project_idfk": 111555,
      "survey_manager": "Kerry Walker",
      "spread_num": 1,
      "spread_city": "Shreveport",
      "spread_state": "Louisiana",
      "supervisor_name": "Matthew George",
      "supervisor_id": 71287,
      "per_diem": 120,
      "mileage": 0.54,
      "vehicle": false,
      "computer": true,
      "phone": true,
      "utv": false,
    },
    {
      "id": 9,
      "project_idfk": 111555,
      "survey_manager": "Kerry Walker",
      "spread_num": 2,
      "spread_city": "Minden",
      "spread_state": "Louisiana",
      "supervisor_name": "Benjamin Wambolt",
      "supervisor_id": 71924,
      "per_diem": 110,
      "mileage": 0.54,
      "vehicle": false,
      "computer": true,
      "phone": true,
      "utv": false,
    },
  ];