export default

  [
    {
      "id": 1,
      "first_name": "Stanford",
      "last_name": "Waganer",
      "nick_name": "Chris",
      "address_st": "98021 Harwin Dr",
      "city": "Houston",
      "address_state": "TX",
      "zip": 77035,
      "phone_1": "713-555-5555",
      "phone_2": "",
      "email": "stanford_waganer@waganer.net",
      "years_experience": 4,
      "prev_position": "PC",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 2,
      "first_name": "Carri",
      "last_name": "Palaspas",
      "nick_name": "",
      "address_st": "51255 Tea Town Rd #9",
      "city": "Shreveport",
      "address_state": "LA",
      "zip": 77777,
      "phone_1": "086-069-1579",
      "phone_2": "",
      "email": "carri_palaspas@palaspas.net",
      "years_experience": 2,
      "prev_position": "IM",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 3,
      "first_name": "Bettyann",
      "last_name": "Fernades",
      "nick_name": "Betty",
      "address_st": "54648 Hylan Blvd #883",
      "city": "Oklahoma City",
      "address_state": "OK",
      "zip": 77777,
      "phone_1": "082-901-3421",
      "phone_2": "",
      "email": "bettyann@fernades.com",
      "years_experience": 1,
      "prev_position": "RM",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 4,
      "first_name": "Kathryn",
      "last_name": "Bonalumi",
      "nick_name": "",
      "address_st": "86 Worth St #272",
      "city": "Tyler",
      "address_state": "TX",
      "zip": 75701,
      "phone_1": "083-071-2258",
      "phone_2": "",
      "email": "kathryn.bonalumi@yahoo.com",
      "years_experience": 10,
      "prev_position": "PC",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 5,
      "first_name": "Desiree",
      "last_name": "Englund",
      "nick_name": "",
      "address_st": "9495 Central Hwy #66",
      "city": "Austin",
      "address_state": "TX",
      "zip": 77035,
      "phone_1": "085-289-4594",
      "phone_2": "",
      "email": "denglund@gmail.com",
      "years_experience": 3,
      "prev_position": "IM",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 6,
      "first_name": "Odelia",
      "last_name": "Hutchin",
      "nick_name": "",
      "address_st": "374 Sunrise Ave",
      "city": "Katy",
      "address_state": "TX",
      "zip": 77035,
      "phone_1": "089-895-1954",
      "phone_2": "",
      "email": "odelia.hutchin@hutchin.com",
      "years_experience": 2,
      "prev_position": "RM",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 7,
      "first_name": "Ethan",
      "last_name": "Quintero",
      "nick_name": "",
      "address_st": "2 Ellis Rd",
      "city": "Lafayette",
      "address_state": "LA",
      "zip": 77035,
      "phone_1": "088-280-9492",
      "phone_2": "",
      "email": "ethan_quintero@quintero.com",
      "years_experience": 20,
      "prev_position": "PC",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 8,
      "first_name": "Tricia",
      "last_name": "Peressini",
      "nick_name": "",
      "address_st": "3 Industrial Blvd",
      "city": "Carencro",
      "address_state": "LA",
      "zip": 77035,
      "phone_1": "084-326-1560",
      "phone_2": "",
      "email": "tperessini@yahoo.com",
      "years_experience": 6,
      "prev_position": "IM",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 9,
      "first_name": "Gerry",
      "last_name": "Mohrmann",
      "nick_name": "",
      "address_st": "8 Glenn Way #3",
      "city": "Dallas",
      "address_state": "TX",
      "zip": 77035,
      "phone_1": "081-399-2471",
      "phone_2": "",
      "email": "gerry_mohrmann@mohrmann.net",
      "years_experience": 1,
      "prev_position": "RM",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 10,
      "first_name": "Jean",
      "last_name": "Cecchinato",
      "nick_name": "",
      "address_st": "7 Hugh Wallis Rd",
      "city": "Tulsa",
      "address_state": "OK",
      "zip": 77035,
      "phone_1": "085-263-2786",
      "phone_2": "",
      "email": "jean.cecchinato@gmail.com",
      "years_experience": 4,
      "prev_position": "IM",
      "comments": "",
      "eligible": true,
      "in_hiring_process": false,
      "hired": false
    },
    {
      "id": 11,
      "first_name": "Laurene",
      "last_name": "Bennett",
      "nick_name": "",
      "address_st": "5 Richmond Ct",
      "city": "Stillwater",
      "address_state": "OK",
      "zip": 77035,
      "phone_1": "082-969-2908",
      "phone_2": "",
      "email": "laurene_bennett@gmail.com",
      "years_experience": 8,
      "prev_position": "PC",
      "comments": "",
      "eligible": true,
      "in_hiring_process": true,
      "hired": false
    },
    {
      "id": 12,
      "first_name": "Miles",
      "last_name": "Feldner",
      "nick_name": "",
      "address_st": "28465 Downey Ave #4238",
      "city": "Minden",
      "address_state": "LA",
      "zip": 77035,
      "phone_1": "078-561-58948",
      "phone_2": "",
      "email": "miles@hotmail.com",
      "years_experience": 3,
      "prev_position": "IM",
      "comments": "",
      "eligible": true,
      "in_hiring_process": true,
      "hired": false
    },
  ];